version: '3.8'

services:
  # Production: Pull from registry
  zammad-mcp:
    image: ghcr.io/basher83/zammad-mcp:latest
    container_name: zammad-mcp
    environment:
      # Zammad configuration - update these values
      ZAMMAD_URL: ${ZAMMAD_URL:-https://your-instance.zammad.com/api/v1}
      ZAMMAD_HTTP_TOKEN: ${ZAMMAD_HTTP_TOKEN}
      # Optional: Use OAuth2 or username/password instead
      # ZAMMAD_OAUTH2_TOKEN: ${ZAMMAD_OAUTH2_TOKEN}
      # ZAMMAD_USERNAME: ${ZAMMAD_USERNAME}
      # ZAMMAD_PASSWORD: ${ZAMMAD_PASSWORD}
    # MCP servers use stdio, not HTTP - uncomment if you add HTTP endpoints
    # ports:
    #   - "8080:8080"
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp:size=100M,mode=1777
      - /app/.cache:size=50M  # For any Python cache needs
    security_opt:
      - no-new-privileges:true
    # Optional: Mount local .env file
    # env_file:
    #   - .env

  # Local build: Build from source (use with --profile local)
  zammad-mcp-local:
    profiles: ["local"]
    build: .
    image: zammad-mcp:local  # Local tag to avoid registry confusion
    container_name: zammad-mcp-local
    environment:
      ZAMMAD_URL: ${ZAMMAD_URL:-https://your-instance.zammad.com/api/v1}
      ZAMMAD_HTTP_TOKEN: ${ZAMMAD_HTTP_TOKEN}
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp:size=100M,mode=1777
      - /app/.cache:size=50M
    security_opt:
      - no-new-privileges:true

# Optional: For development with hot reload
  zammad-mcp-dev:
    profiles: ["dev"]
    build: 
      context: .
      target: development
    volumes:
      - ./mcp_zammad:/app/mcp_zammad
      - ./.env:/app/.env:ro
    environment:
      ZAMMAD_URL: ${ZAMMAD_URL:-https://your-instance.zammad.com/api/v1}
      ZAMMAD_HTTP_TOKEN: ${ZAMMAD_HTTP_TOKEN}
    # Development might need ports for debugging tools
    # ports:
    #   - "8081:8080"
    # Development needs write access for hot reload and .pyc files
    # read_only: true  # Disabled for development
    security_opt:
      - no-new-privileges:true
    command: ["uv", "run", "--watch", "mcp-zammad"]