name: Tests and Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: 'uv.lock'

      - name: Install dependencies
        run: |
          uv sync --dev --frozen

      - name: Run tests with coverage
        run: |
          # Run pytest with coverage in XML format for Codacy
          uv run pytest tests/ \
            --cov=mcp_zammad \
            --cov-report=xml:coverage.xml \
            --cov-report=term-missing \
            --cov-report=html:htmlcov

      - name: Upload coverage to Codacy
        # Only upload on push to main or PRs (not on manual triggers)
        if: github.event_name != 'workflow_dispatch'
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml
          language: python

      - name: Upload coverage reports as artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-reports
          path: |
            coverage.xml
            htmlcov/

      - name: Generate Coverage Summary
        if: always()
        run: |
          echo "## 📊 Test Coverage Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ -f coverage.xml ]; then
            # Parse coverage.xml to extract percentage
            COVERAGE=$(python -c "import xml.etree.ElementTree as ET; tree = ET.parse('coverage.xml'); root = tree.getroot(); coverage = float(root.get('line-rate', 0)) * 100; print(f'{coverage:.1f}')")
            
            echo "### Overall Coverage: ${COVERAGE}%" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            
            # Coverage badge
            COVERAGE=$COVERAGE python -c "import os; cov = float(os.environ['COVERAGE']); print('✅ **Status**: Good coverage (target: 80%)' if cov >= 80 else '⚠️ **Status**: Moderate coverage (target: 80%)' if cov >= 60 else '❌ **Status**: Low coverage (target: 80%)')" >> $GITHUB_STEP_SUMMARY
            
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "📈 Coverage details available in [Codacy](https://app.codacy.com)" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Coverage report not generated" >> $GITHUB_STEP_SUMMARY
          fi